# Generated by Django 4.2 on 2023-08-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('place_name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('phone_no', models.IntegerField(max_length=10)),
                ('number_of_passenger', models.IntegerField(max_length=50)),
                ('vehicle_required', models.CharField(max_length=100)),
            ],
        ),
    ]
